export const REVIEW_PHONE = [
  {
    device: 'phones',
    author: 'Ronald',
    rating: 4.5,
    message: `Great phone for everyday use, What you should pay attention to with newer phones and tablets is that there is no headphone jack. you don't always want bluetooth, but also wired headphones. there is another option to plug a converter for that into the charging usb socket.`,
    pros: ['Long battery life', 'Relatively cheap'],
    cons: ['No 3.5mm jack'],
  },
  {
    device: 'phones',
    author: 'Ben',
    rating: 4.5,
    message: `Great device for a reasonable price, You really don't need a device of 1000+ euros. This device can do everything and for a reasonable price.`,
    pros: [
      'Nice bright screen',
      'Useful samsung apps such as health and password manager',
    ],
    cons: ['Still occasional delays in apps'],
  },
  {
    device: 'phones',
    author: 'Michael',
    rating: 5,
    message: `Great purchase. Device bought as a replacement for a Nokia 8. Transfer all apps and settings quickly and without too much hassle. It takes some getting used to from a bare android UI to the Samsung UI. Fortunately, all bloatware is easy to remove. The camera is fine (especially compared to that of the Nokia 8) and there is nothing wrong with the battery life. The device is not used very intensively; I already got a battery life of three days.`,
    pros: ['battery life', 'long support'],
    cons: ['a lot of bloatware', 'Samsung UI takes getting used to'],
  },
  {
    device: 'phones',
    author: 'Sophia',
    rating: 4.5,
    message: `good phone for a good price`,
    pros: [
      'Takes very good sharp photos',
      'Sufficient working memory, so you can switch smoothly between different apps',
    ],
    cons: ['No charger is included'],
  },
  {
    device: 'phones',
    author: 'Alexander',
    rating: 4,
    message: `Great phone, very fast to install, just wow, my daughter is very happy with it`,
    pros: ['Battery is great! I last longer than 24 hours'],
    cons: [
      'A little slow',
      'no charger was included, the explanation was vague',
    ],
  },
  {
    device: 'phones',
    author: 'Chris',
    rating: 4,
    message: `Nice fast mobile. Very big. Doesn't sit well in your pocket.`,
    pros: ['Battery', 'Screen'],
    cons: [
      'Very big for a trouser pocket',
      'no charger was included, the explanation was vague',
    ],
  },
  {
    device: 'phones',
    author: 'Frank',
    rating: 3.5,
    message: `Slower and hypersensitive screen when entering text`,
    pros: ['Display', 'Easily transfer data.'],
    cons: ['Keyboard operation hypersensitive'],
  },
  {
    device: 'phones',
    author: 'Erika',
    rating: 2,
    message: `battery was crap, returned within 1 week`,
    pros: [],
    cons: ['battery drained within 6 hours after 1 day'],
  },
  {
    device: 'phones',
    author: 'John',
    rating: 1.5,
    message: `Didn't receive it!`,
    pros: [],
    cons: [],
  },
  {
    device: 'phones',
    author: 'Peter',
    rating: 3,
    message: `Too expensive for what it is`,
    pros: ['Good camera'],
    cons: [
      'Not user-friendly',
      'Price-performance ratio',
      'Performance behavior',
    ],
  },
  {
    device: 'phones',
    author: 'Rick',
    rating: 2.5,
    message: `Well for the price I expected more from the phone`,
    pros: [],
    cons: ['Battery is just “bad”', 'A big black pixel on my screen'],
  },
  {
    device: 'phones',
    author: 'Bogdan',
    rating: 2,
    message: `Very bad product. After approximately 9 month of usage phone got impossible to work with - no sound during calls (only using the speaker), very slow response, activating keys and screenshots in pocket`,
    pros: [],
    cons: ['Empty quickly'],
  },
  {
    device: 'phones',
    author: 'Kevin',
    rating: 2.5,
    message: `Just new: Screen sometimes stays black for seconds after pressing the power button. Seems to get stuck sometimes and with calls it sometimes also cuts out, disconnects.`,
    pros: [],
    cons: ['Slow response / hangs', 'Disconnects from calling'],
  },
  {
    device: 'phones',
    author: 'Jan',
    rating: 3,
    message: `very disappointed. have taken medium level phones for years and expected much more quality and battery life from a sub top model`,
    pros: ['if it works, smooth', 'Looks sleek'],
    cons: ['apps close randomly', 'gets super hot'],
  },
  {
    device: 'phones',
    author: 'Debbie',
    rating: 3.5,
    message: `Everything except typing or scrolling is beautiful
    Swipe to type doesn't go without breaks in every word.`,
    pros: ['Takes great photos'],
    cons: ['touch screen is ok at best', 'dark / light not well adjustable'],
  },
  {
    device: 'phones',
    author: 'Tamara',
    rating: 1,
    message: `Bad customer service. help no further. I never got it delivered`,
    pros: [],
    cons: [],
  },
  {
    device: 'phones',
    author: 'Sam',
    rating: 3.5,
    message: `It's not a bad phone, but the phone is way too expensive for what you end up getting. E.g. an LCD screen that is something that even budget phones no longer have these days. The 12-megapixel camera is also something that doesn't belong here. Easy to use. If you want a nice screen and a really good camera I wouldn't buy this but if you're looking for a phone that's easy to use this is a good option if you don't consider the price.`,
    pros: ['Easy to use'],
    cons: ['Bad camera', 'Bad display', 'Low value for money'],
  },
  {
    device: 'phones',
    author: 'Nicky',
    rating: 3.5,
    message: `Beautiful but too heavy, overall, I regret the purchase.`,
    pros: ['Photos are beautiful'],
    cons: ['Expensive device', 'Too big and too heavy'],
  },
];
