export const REVIEW_LAPTOP = [
  {
    device: 'laptops',
    author: 'Charlotte',
    rating: 5,
    message: `The laptop is fast, has a large screen and a lot of memory.
    The real downside is the lack of a hole for an anti-theft cable. The other negatives are more comments than real negatives.`,
    pros: ['Very fast machine', 'Boot quickly under Windows 11'],
    cons: ['No lock for anti-theft lock', ''],
  },
  {
    device: 'laptops',
    author: 'Erik',
    rating: 4.5,
    message: `A nice device for me. The fact that the battery runs out quickly is not a big problem for me because the laptop will usually be attached to the power cord.`,
    pros: ['Image quality', 'Speed'],
    cons: ['Battery drains quickly'],
  },
  {
    device: 'laptops',
    author: 'Willem',
    rating: 4,
    message: `Very good performance laptop with beautiful white design and blue LEDs. Heavy, so not for daily wear (Biggest power adapter I've ever seen).
    On the table, at home, perfect for gaming
    `,
    pros: [
      'Balance mode is good enough for most gaming. You need it for rest. Performance mode is very loud with the fans',
      'Not too much bloatware. Except for Windows 11',
    ],
    cons: ['Fans are loud in Performance mode'],
  },
  {
    device: 'laptops',
    author: 'Mitchell',
    rating: 4,
    message: `Very solid device, super fast, a lot of memory capacity and a very good processor and video card. In addition, it also looks beautiful.
    `,
    pros: ['RGB keyboard', 'sleek design', 'Strong gaming laptop'],
    cons: [
      'Battery life is unfortunately not that great but nevertheless a top laptop',
    ],
  },
  {
    device: 'laptops',
    author: 'Henk',
    rating: 5,
    message: `This laptop is fast and versatile with a nice keyboard. You can work on it and take it with you on a trip, etc.`,
    pros: [
      'Device is fast and versatile',
      'Word processing and internet browsing is fast.',
    ],
    cons: ['Couldnt find a flaw so far.'],
  },
  {
    device: 'laptops',
    author: 'Caroline',
    rating: 2,
    message: `Bad experience working with Teams in terms of sound, image and stability.`,
    pros: [],
    cons: ['Sound and picture is of lower quality'],
  },
  {
    device: 'laptops',
    author: 'Mark',
    rating: 4,
    message: `Very nice compact laptop! Very light so easy to carry. Nice that you can also work well in the evening by means of the luminous keyboard`,
    pros: [
      'Luminous Keyboard',
      'black keyboard, so clearly visible on a silver laptop',
    ],
    cons: ['not extremely fast, but fine for the normal user'],
  },
  {
    device: 'laptops',
    author: 'Liam',
    rating: 5,
    message: `The laptop is excellent and more than meets the expectations`,
    pros: ['Very fast', 'firm', 'low weight'],
    cons: ['Delete and on/off button are close to each other'],
  },
  {
    device: 'laptops',
    author: 'Emma',
    rating: 4.5,
    message: `The product is nicely finished and the speed is nice for my light business use. From text to film/photo editing`,
    pros: ['Super-fast start-up', 'Speed', 'Brightness'],
    cons: ['Unwelcome advertising + offers'],
  },
  {
    device: 'laptops',
    author: 'Karel',
    rating: 3.5,
    message: `Almost perfect laptop for this price, battery life is very disappointing.`,
    pros: ['keyboard lighting', 'Great for Word, Netflix and the web'],
    cons: ['Battery life'],
  },
  {
    device: 'laptops',
    author: 'Amelia',
    rating: 4.5,
    message: `A not-too-expensive laptop that's great for Word, browsing the web, and watching movies. Very happy that this laptop has an ethernet port, because this is no longer the case with all laptop pens!`,
    pros: ['Battery lasts a long time', 'HDMI and Ethernet ports'],
    cons: ['Makes quite a bit of noise every now and then'],
  },
  {
    device: 'laptops',
    author: 'Olivia',
    rating: 4.5,
    message: `Bought this laptop especially for Hogwards Legacy, so far flawless`,
    pros: [
      'I can play hogwards legacy on high settings',
      'Thats the main plus point anyway',
    ],
    cons: ['Loud fan'],
  },
  {
    device: 'laptops',
    author: 'Noah',
    rating: 4,
    message: `So far only good experience.... still have to get used to the keyboard with the game... My previous one was a bit wider but the screen is the same size... I recommend it`,
    pros: ['sharp image for both gaming and watching movies', 'Graphics'],
    cons: [],
  },
  {
    device: 'laptops',
    author: 'Adinda',
    rating: 4,
    message: `Is more than enough for work without heavy graphics needs`,
    pros: ['Quiet', 'Fast performance'],
    cons: ['Battery life not nearly what is claimed'],
  },
  {
    device: 'laptops',
    author: 'Mohamed',
    rating: 3.5,
    message: `Top laptop for multitasking and daily use, only the battery is really bad. Not recommended if you're looking for a laptop that lasts longer or comes close to the claimed battery life`,
    pros: ['User friendly', 'Fast booting with SSD'],
    cons: ['Battery life is really really bad, not as described'],
  },
  {
    device: 'laptops',
    author: 'Peter',
    rating: 3.5,
    message: `Beautiful laptop alone, according to the Samsung site, you should be able to add memory, but that must be done via a Samsung service and your warranty would no longer be valid. That's a shame to say the least.`,
    pros: [],
    cons: ['memory should be 1 Tb', 'battery doesnt last as long as it says'],
  },
  {
    device: 'laptops',
    author: 'Jonathan',
    rating: 5,
    message: `been a good purchase. no regrets. Fast and works properly.`,
    pros: ['Good processor', 'Numeric keypad'],
    cons: ['No Ethernet port', 'No keyboard backlight'],
  },
  {
    device: 'laptops',
    author: 'Steven',
    rating: 2.5,
    message: `Handy laptop to take with you, but a lot is missing`,
    pros: ['it is light and compact. Handy to take with you'],
    cons: [
      'annoying keyboard',
      'No key illumination',
      'Accounting program Snelstart does not work on new version of Microsoft',
    ],
  },
];
