import { Category, CatalogItem } from '../types';

export const phones = [
  {
    id: 1,
    category: Category.phones,
    model: 'Samsung Galaxy A73 2022 A736B 8/256GB Gray (SM-A736BZAHSEK)',
    mainPhoto:
      'https://content.rozetka.com.ua/goods/images/big_tile/263857428.jpg',
    rating: 4.5,
    bestSeller: false,
    totalPrice: 550,
    discountedPrice: 550,
    shortSpecs: [
      ['Display', 'Super AMOLED Display'],
      ['Screen Size', '6.5 inch'],
      ['Weights', '189g'],
      ['Processor', 'Mediatek Helio G96'],
      ['Camera', '108 Mp + 8 Mp + 2 Mp + 2 Mp'],
      ['Battery', '5000mAh'],
    ],
  },
  {
    id: 2,
    category: Category.phones,
    model: 'realme 10 4G 8/128GB (Rush Black)',
    mainPhoto:
      'https://www.ctrs.com.ua/_next/image/?url=https://i.citrus.world/imgcache/size_180/uploads/shop/d/3/d3377115cec2bf49ea5b21a3ee6a0c2a.jpg&w=256&q=60',
    rating: 4.3,
    bestSeller: false,
    totalPrice: 450,
    discountedPrice: 450,
    shortSpecs: [
      ['Display', 'Super AMOLED Display'],
      ['Screen Size', '6.5 inch'],
      ['Weights', '189g'],
      ['Processor', 'Mediatek Helio G96'],
      ['Camera', '108 Mp + 8 Mp + 2 Mp + 2 Mp'],
      ['Battery', '5000mAh'],
    ],
  },
  {
    id: 3,
    category: Category.phones,
    model: 'OPPO A17k 3/64GB (Blue)',
    mainPhoto:
      'https://i.citrus.world/imgcache/size_180/uploads/shop/b/8/b8236485187b5143fcc0d5c8bd6a3f10.jpg',
    rating: 4.7,
    bestSeller: true,
    totalPrice: 350,
    discountedPrice: 300,
    shortSpecs: [
      ['Display', 'Super AMOLED Display'],
      ['Screen Size', '6.5 inch'],
      ['Weights', '189g'],
      ['Processor', 'Mediatek Helio G96'],
      ['Camera', '108 Mp + 8 Mp + 2 Mp + 2 Mp'],
      ['Battery', '5000mAh'],
    ],
  },
  {
    id: 4,
    category: Category.phones,
    model: 'Samsung Galaxy A73 2022 A736B 8/256GB Gray (SM-A736BZAHSEK)',
    mainPhoto:
      'https://content.rozetka.com.ua/goods/images/big_tile/263857428.jpg',
    rating: 4.5,
    bestSeller: true,
    totalPrice: 550,
    discountedPrice: 500,
    shortSpecs: [
      ['Display', 'Super AMOLED Display'],
      ['Screen Size', '6.5 inch'],
      ['Weights', '189g'],
      ['Processor', 'Mediatek Helio G96'],
      ['Camera', '108 Mp + 8 Mp + 2 Mp + 2 Mp'],
      ['Battery', '5000mAh'],
    ],
  },
  {
    id: 5,
    category: Category.phones,
    model: 'Samsung Galaxy A73 2022 A736B 8/256GB Gray (SM-A736BZAHSEK)',
    mainPhoto:
      'https://content.rozetka.com.ua/goods/images/big_tile/263857428.jpg',
    rating: 4.5,
    bestSeller: true,
    totalPrice: 550,
    discountedPrice: 510,
    shortSpecs: [
      ['Display', 'Super AMOLED Display'],
      ['Screen Size', '6.5 inch'],
      ['Weights', '189g'],
      ['Processor', 'Mediatek Helio G96'],
      ['Camera', '108 Mp + 8 Mp + 2 Mp + 2 Mp'],
      ['Battery', '5000mAh'],
    ],
  },
  {
    id: 6,
    category: Category.phones,
    model: 'Samsung Galaxy A73 2022 A736B 8/256GB Gray (SM-A736BZAHSEK)',
    mainPhoto:
      'https://content.rozetka.com.ua/goods/images/big_tile/263857428.jpg',
    rating: 4.5,
    bestSeller: true,
    totalPrice: 550,
    discountedPrice: 550,
    shortSpecs: [
      ['Display', 'Super AMOLED Display'],
      ['Screen Size', '6.5 inch'],
      ['Weights', '189g'],
      ['Processor', 'Mediatek Helio G96'],
      ['Camera', '108 Mp + 8 Mp + 2 Mp + 2 Mp'],
      ['Battery', '5000mAh'],
    ],
  },
  {
    id: 7,
    category: Category.phones,
    model: 'Samsung Galaxy A73 2022 A736B 8/256GB Gray (SM-A736BZAHSEK)',
    mainPhoto:
      'https://content.rozetka.com.ua/goods/images/big_tile/263857428.jpg',
    rating: 4.5,
    bestSeller: true,
    totalPrice: 550,
    discountedPrice: 480,
    shortSpecs: [
      ['Display', 'Super AMOLED Display'],
      ['Screen Size', '6.5 inch'],
      ['Weights', '189g'],
      ['Processor', 'Mediatek Helio G96'],
      ['Camera', '108 Mp + 8 Mp + 2 Mp + 2 Mp'],
      ['Battery', '5000mAh'],
    ],
  },
  {
    id: 8,
    category: Category.phones,
    model: 'Samsung Galaxy A73 2022 A736B 8/256GB Gray (SM-A736BZAHSEK)',
    mainPhoto:
      'https://content.rozetka.com.ua/goods/images/big_tile/263857428.jpg',
    rating: 4.5,
    bestSeller: true,
    totalPrice: 550,
    discountedPrice: 470,
    shortSpecs: [
      ['Display', 'Super AMOLED Display'],
      ['Screen Size', '6.5 inch'],
      ['Weights', '189g'],
      ['Processor', 'Mediatek Helio G96'],
      ['Camera', '108 Mp + 8 Mp + 2 Mp + 2 Mp'],
      ['Battery', '5000mAh'],
    ],
  },
  {
    id: 9,
    category: Category.phones,
    model: 'Samsung Galaxy A73 2022 A736B 8/256GB Gray (SM-A736BZAHSEK)',
    mainPhoto:
      'https://content.rozetka.com.ua/goods/images/big_tile/263857428.jpg',
    rating: 4.5,
    bestSeller: true,
    totalPrice: 550,
    discountedPrice: 510,
    shortSpecs: [
      ['Display', 'Super AMOLED Display'],
      ['Screen Size', '6.5 inch'],
      ['Weights', '189g'],
      ['Processor', 'Mediatek Helio G96'],
      ['Camera', '108 Mp + 8 Mp + 2 Mp + 2 Mp'],
      ['Battery', '5000mAh'],
    ],
  },
  {
    id: 10,
    category: Category.phones,
    model: 'Samsung Galaxy A73 2022 A736B 8/256GB Gray (SM-A736BZAHSEK)',
    mainPhoto:
      'https://content.rozetka.com.ua/goods/images/big_tile/263857428.jpg',
    rating: 4.5,
    bestSeller: true,
    totalPrice: 550,
    discountedPrice: 550,
    shortSpecs: [
      ['Display', 'Super AMOLED Display'],
      ['Screen Size', '6.5 inch'],
      ['Weights', '189g'],
      ['Processor', 'Mediatek Helio G96'],
      ['Camera', '108 Mp + 8 Mp + 2 Mp + 2 Mp'],
      ['Battery', '5000mAh'],
    ],
  },
  {
    id: 11,
    category: Category.phones,
    model: 'Samsung Galaxy A73 2022 A736B 8/256GB Gray (SM-A736BZAHSEK)',
    mainPhoto:
      'https://content.rozetka.com.ua/goods/images/big_tile/263857428.jpg',
    rating: 4.5,
    bestSeller: true,
    totalPrice: 550,
    discountedPrice: 550,
    shortSpecs: [
      ['Display', 'Super AMOLED Display'],
      ['Screen Size', '6.5 inch'],
      ['Weights', '189g'],
      ['Processor', 'Mediatek Helio G96'],
      ['Camera', '108 Mp + 8 Mp + 2 Mp + 2 Mp'],
      ['Battery', '5000mAh'],
    ],
  },
  {
    id: 12,
    category: Category.phones,
    model: 'Samsung Galaxy A73 2022 A736B 8/256GB Gray (SM-A736BZAHSEK)',
    mainPhoto:
      'https://content.rozetka.com.ua/goods/images/big_tile/263857428.jpg',
    rating: 4.5,
    bestSeller: true,
    totalPrice: 550,
    discountedPrice: 550,
    shortSpecs: [
      ['Display', 'Super AMOLED Display'],
      ['Screen Size', '6.5 inch'],
      ['Weights', '189g'],
      ['Processor', 'Mediatek Helio G96'],
      ['Camera', '108 Mp + 8 Mp + 2 Mp + 2 Mp'],
      ['Battery', '5000mAh'],
    ],
  },
  {
    id: 13,
    category: Category.phones,
    model: 'Samsung Galaxy A73 2022 A736B 8/256GB Gray (SM-A736BZAHSEK)',
    mainPhoto:
      'https://content.rozetka.com.ua/goods/images/big_tile/263857428.jpg',
    rating: 4.5,
    bestSeller: true,
    totalPrice: 550,
    discountedPrice: 520,
    shortSpecs: [
      ['Display', 'Super AMOLED Display'],
      ['Screen Size', '6.5 inch'],
      ['Weights', '189g'],
      ['Processor', 'Mediatek Helio G96'],
      ['Camera', '108 Mp + 8 Mp + 2 Mp + 2 Mp'],
      ['Battery', '5000mAh'],
    ],
  },
] as CatalogItem[];
