import { CategoryUpercase, Product, Specification, SpecsBrief } from '../types';

export const product = [
  {
    category: CategoryUpercase.laptop,
    comments: 9,
    specsBriefIcon: {
      diagonal: '15,6"',
      memory: '256 Gb',
      os: 'DOS',
      processor: 'Intel Celeron N4120',
      ram: '16 Gb',
      gpu: 'Intel UHD Graphics 600',
    } as SpecsBrief,
    photos: [
      'https://scdn.comfy.ua/89fc351a-22e7-41ee-8321-f8a9356ca351/https://cdn.comfy.ua/media/catalog/product/z/q/zqn8vnvy.jpg/w_600',
      'https://scdn.comfy.ua/89fc351a-22e7-41ee-8321-f8a9356ca351/https://cdn.comfy.ua/media/catalog/product/1/1/11_ideapad_gaming_3_hero_front_semi_closed.jpg/w_600',
      'https://scdn.comfy.ua/89fc351a-22e7-41ee-8321-f8a9356ca351/https://cdn.comfy.ua/media/catalog/product/0/6/06_ideapad_gaming_3_hero_left_profile.jpg/w_600',
      'https://scdn.comfy.ua/89fc351a-22e7-41ee-8321-f8a9356ca351/https://cdn.comfy.ua/media/catalog/product/0/2/02_ideapad_gaming_3_hero_front_facing_right.jpg/w_600',
      'https://scdn.comfy.ua/89fc351a-22e7-41ee-8321-f8a9356ca351/https://cdn.comfy.ua/media/catalog/product/0/5/05_ideapad_gaming_3_hero_right_profile.jpg/w_600',
      'https://scdn.comfy.ua/89fc351a-22e7-41ee-8321-f8a9356ca351/https://cdn.comfy.ua/media/catalog/product/1/0/10_ideapad_gaming_3_hero_a_cover.jpg/w_600',
      'https://scdn.comfy.ua/89fc351a-22e7-41ee-8321-f8a9356ca351/https://cdn.comfy.ua/media/catalog/product/0/8/08_ideapad_gaming_3_hero_a_d_cover.jpg/w_600',
    ],
    specifications: {
      display: {
        'Display diagonal': '15.6 " (39,6 cm)',
        'Display resolution': '1920 x 1080 pixels',
        'Panel type': 'IPS',
        'Native aspect ratio': '16:9',
        'Anti-glare screen': 'Yes',
        'Display brightness': '250 cd/m²',
        'RGB color space': 'NTSC',
        'Maximum refresh rate': '120 Hz',
        'Contrast ratio (typical)': '800:1',
      },
      processor: {
        'Processor family': 'AMD Ryzen™ 5',
        'Processor manufacturer': 'AMD',
        'Processor frequency': '3,3 GHz',
        'Processor boost frequency': '4,2 GHz',
        'Processor cores': '6',
        'Processor cache': '16 MB',
      },
      memory: {
        'Internal memory': '8 GB',
        'Maximum internal memory': '16 GB',
        'Internal memory type': 'DDR4-SDRAM',
        'Memory clock speed': '3200 MHz',
        'Memory layout (slots x size)': '1 x 8 GB',
      },
      storage: {
        'Total storage capacity': '512 GB',
        'Storage media': 'SSD',
        'Total SSDs capacity': '512 GB',
        'Number of SSDs installed': '1',
        'SSD capacity': '512 GB',
      },
      graphics: {
        'On-board graphics card': 'Yes',
        'Discrete graphics card model': 'NVIDIA GeForce RTX 3060',
        'On-board graphics card model': 'AMD Radeon Graphics',
        'Discrete GPU manufacturer': 'NVIDIA',
        'Discrete graphics card memory': '6 GB',
      },
      audio: {
        'Audio chip': 'Realtek ALC3287',
        'Number of built-in speakers': '2',
        'Speaker power': '2 W',
        'Built-in microphone': 'Yes',
      },
      camera: {
        'Front camera': 'Yes',
        'Front camera resolution': '1280 x 720 pixels',
        'Front camera HD type': 'HD',
      },
      network: {
        'Mobile network connection': 'No',
        'Top Wi-Fi standard': 'Wi-Fi 6 (802.11ax)',
        'Antenna type': '2x2',
        'Ethernet LAN': 'Yes',
        'Ethernet LAN data rates': '100,1000 Mbit/s',
        Bluetooth: 'Yes',
      },
      'Ports & interfaces': {
        'USB 3.2 Gen 1 (3.1 Gen 1) Type-A ports quantity': '2',
        'USB 3.2 Gen 1 (3.1 Gen 1) Type-C ports quantity': '1',
        'HDMI ports quantity': '1',
        'Ethernet LAN (RJ-45) ports': '1',
      },
      battery: {
        'Battery capacity': '45 Wh',
        'Battery technology': 'Lithium Polymer (LiPo)',
        'Battery life (max)': '5 h',
      },
      'Weight & dimensions': {
        Weight: '5 lbs (2,25 kg)',
        Width: '14.2 " (359,6 mm)',
        Depth: '9.9 " (251,9 mm)',
        Height: '1 " (24,2 mm)',
      },
    } as Specification,
  },
  {
    category: CategoryUpercase.tablet,
    comments: 8,
    specsBriefIcon: {
      diagonal: '10.5"',
      screenType: 'WUGHA',
      os: 'Android 11',
      processor: 'Unisoc Tiger T618',
      ram: '4 Gb',
      memory: '64 GB',
    } as SpecsBrief,
    photos: [
      'https://i.citrus.world/imgcache/size_800/uploads/shop/1/0/1063856dd2688ed21280e6db1bb25ec1.jpg',
      'https://i.citrus.world/imgcache/size_800/uploads/shop/0/e/0e84c4bffedbaaa39f52f914530f661d.jpg',
      'https://i.citrus.world/imgcache/size_800/uploads/shop/2/e/2e73eef78fbfa83666cf4f1563a51337.jpg',
      'https://i.citrus.world/imgcache/size_800/uploads/shop/9/3/932f3b9a409054a043cf0cb57717c066.jpg',
      'https://i.citrus.world/imgcache/size_800/uploads/shop/4/9/493a00551ea6c9ecbb0890722bb8fdad.jpg',
      'https://i.citrus.world/imgcache/size_800/uploads/shop/2/1/218ec839a33ff9792de39366159ba04e.jpg',
      'https://i.citrus.world/imgcache/size_800/uploads/shop/0/d/0d7002700b28e1f9653ffa08bdcafd03.jpg',
    ],
    specifications: {
      display: {
        'Display diagonal': '15.6 " (39,6 cm)',
        'Display resolution': '1920 x 1080 pixels',
        'Panel type': 'IPS',
        'Native aspect ratio': '16:9',
        'Anti-glare screen': 'Yes',
        'Display brightness': '250 cd/m²',
        'RGB color space': 'NTSC',
        'Maximum refresh rate': '120 Hz',
        'Contrast ratio (typical)': '800:1',
      },
      processor: {
        'Processor family': 'AMD Ryzen™ 5',
        'Processor manufacturer': 'AMD',
        'Processor frequency': '3,3 GHz',
        'Processor boost frequency': '4,2 GHz',
        'Processor cores': '6',
        'Processor cache': '16 MB',
      },
      memory: {
        'Internal memory': '8 GB',
        'Maximum internal memory': '16 GB',
        'Internal memory type': 'DDR4-SDRAM',
        'Memory clock speed': '3200 MHz',
        'Memory layout (slots x size)': '1 x 8 GB',
      },
      storage: {
        'Total storage capacity': '512 GB',
        'Storage media': 'SSD',
        'Total SSDs capacity': '512 GB',
        'Number of SSDs installed': '1',
        'SSD capacity': '512 GB',
      },
      graphics: {
        'On-board graphics card': 'Yes',
        'Discrete graphics card model': 'NVIDIA GeForce RTX 3060',
        'On-board graphics card model': 'AMD Radeon Graphics',
        'Discrete GPU manufacturer': 'NVIDIA',
        'Discrete graphics card memory': '6 GB',
      },
      audio: {
        'Audio chip': 'Realtek ALC3287',
        'Number of built-in speakers': '2',
        'Speaker power': '2 W',
        'Built-in microphone': 'Yes',
      },
      camera: {
        'Front camera': 'Yes',
        'Front camera resolution': '1280 x 720 pixels',
        'Front camera HD type': 'HD',
      },
      network: {
        'Mobile network connection': 'No',
        'Top Wi-Fi standard': 'Wi-Fi 6 (802.11ax)',
        'Antenna type': '2x2',
        'Ethernet LAN': 'Yes',
        'Ethernet LAN data rates': '100,1000 Mbit/s',
        Bluetooth: 'Yes',
      },
      'Ports & interfaces': {
        'USB 3.2 Gen 1 (3.1 Gen 1) Type-A ports quantity': '2',
        'USB 3.2 Gen 1 (3.1 Gen 1) Type-C ports quantity': '1',
        'HDMI ports quantity': '1',
        'Ethernet LAN (RJ-45) ports': '1',
      },
      battery: {
        'Battery capacity': '45 Wh',
        'Battery technology': 'Lithium Polymer (LiPo)',
        'Battery life (max)': '5 h',
      },
      'Weight & dimensions': {
        Weight: '5 lbs (2,25 kg)',
        Width: '14.2 " (359,6 mm)',
        Depth: '9.9 " (251,9 mm)',
        Height: '1 " (24,2 mm)',
      },
    } as Specification,
  },
  {
    category: CategoryUpercase.phone,
    comments: 5,
    specsBriefIcon: {
      diagonal: '6.7"',
      camera: '108,0 Mp + 12,0 Mp + 5,0 Mp + 5,0 Mp',
      selfieCamera: '32 Mp',
      processor: 'Qualcomm Snapdragon 778G',
      core: 'Octa-Core (8)',
      battery: '5000 mAh',
    } as SpecsBrief,
    photos: [
      'https://i.citrus.world/imgcache/size_800/uploads/shop/d/3/d3377115cec2bf49ea5b21a3ee6a0c2a.jpg',
      'https://i.citrus.world/imgcache/size_800/uploads/shop/0/2/023f8e6f9e03c6a6cfe8fe0cf162c44d.jpg',
      'https://i.citrus.world/imgcache/size_800/uploads/shop/8/b/8b95b3336332f60b0b93d15e625f3eb0.jpg',
      'https://i.citrus.world/imgcache/size_800/uploads/shop/5/6/568f733c54b35d10081cf8e1b373b377.jpg',
      'https://i.citrus.world/imgcache/size_800/uploads/shop/9/1/91e2dd97d09c4274c02455d612e24558.jpg',
      'https://i.citrus.world/imgcache/size_800/uploads/shop/d/7/d788911842e42c47e8d6957cf50f2932.jpg',
      'https://i.citrus.world/imgcache/size_800/uploads/shop/e/4/e4da144b266fdbc45fff167257f494e9.jpg',
    ],
    specifications: {
      display: {
        'Display diagonal': '15.6 " (39,6 cm)',
        'Display resolution': '1920 x 1080 pixels',
        'Panel type': 'IPS',
        'Native aspect ratio': '16:9',
        'Anti-glare screen': 'Yes',
        'Display brightness': '250 cd/m²',
        'RGB color space': 'NTSC',
        'Maximum refresh rate': '120 Hz',
        'Contrast ratio (typical)': '800:1',
      },
      processor: {
        'Processor family': 'AMD Ryzen™ 5',
        'Processor manufacturer': 'AMD',
        'Processor frequency': '3,3 GHz',
        'Processor boost frequency': '4,2 GHz',
        'Processor cores': '6',
        'Processor cache': '16 MB',
      },
      memory: {
        'Internal memory': '8 GB',
        'Maximum internal memory': '16 GB',
        'Internal memory type': 'DDR4-SDRAM',
        'Memory clock speed': '3200 MHz',
        'Memory layout (slots x size)': '1 x 8 GB',
      },
      storage: {
        'Total storage capacity': '512 GB',
        'Storage media': 'SSD',
        'Total SSDs capacity': '512 GB',
        'Number of SSDs installed': '1',
        'SSD capacity': '512 GB',
      },
      graphics: {
        'On-board graphics card': 'Yes',
        'Discrete graphics card model': 'NVIDIA GeForce RTX 3060',
        'On-board graphics card model': 'AMD Radeon Graphics',
        'Discrete GPU manufacturer': 'NVIDIA',
        'Discrete graphics card memory': '6 GB',
      },
      audio: {
        'Audio chip': 'Realtek ALC3287',
        'Number of built-in speakers': '2',
        'Speaker power': '2 W',
        'Built-in microphone': 'Yes',
      },
      camera: {
        'Front camera': 'Yes',
        'Front camera resolution': '1280 x 720 pixels',
        'Front camera HD type': 'HD',
      },
      network: {
        'Mobile network connection': 'No',
        'Top Wi-Fi standard': 'Wi-Fi 6 (802.11ax)',
        'Antenna type': '2x2',
        'Ethernet LAN': 'Yes',
        'Ethernet LAN data rates': '100,1000 Mbit/s',
        Bluetooth: 'Yes',
      },
      'Ports & interfaces': {
        'USB 3.2 Gen 1 (3.1 Gen 1) Type-A ports quantity': '2',
        'USB 3.2 Gen 1 (3.1 Gen 1) Type-C ports quantity': '1',
        'HDMI ports quantity': '1',
        'Ethernet LAN (RJ-45) ports': '1',
      },
      battery: {
        'Battery capacity': '45 Wh',
        'Battery technology': 'Lithium Polymer (LiPo)',
        'Battery life (max)': '5 h',
      },
      'Weight & dimensions': {
        Weight: '5 lbs (2,25 kg)',
        Width: '14.2 " (359,6 mm)',
        Depth: '9.9 " (251,9 mm)',
        Height: '1 " (24,2 mm)',
      },
    } as Specification,
  },
] as Product[];
