import { Category, CatalogItem } from '../types';

export const tablets = [
  {
    category: Category.tablets,
    name: 'Samsung Galaxy Tab S7 FE LTE 64GB Black (SM-T735NZKASEK)',
    model: 'samsung-galaxy-tab-s7-fe-lte-64gb-black-sm-t735nzkasek',
    mainPhoto:
      'https://content1.rozetka.com.ua/goods/images/big_tile/194432937.jpg',
    rating: 4.5,
    bestSeller: true,
    totalPrice: 650,
    discountedPrice: 620,
    shortSpecs: [
      ['Display', 'Retina'],
      ['Screen Size', '12.4 inch'],
      ['Processor', 'Qualcomm Snapdragon 750G'],
      ['CPU Cores', '8'],
      ['Memory Storage Capacity', '64 GB'],
    ],
  },
  {
    category: Category.tablets,
    name: 'Apple iPad 9 10.2" 64GB Wi-Fi Space Grey (MK2K3) 2021',
    model: 'apple-ipad-9-10-2-64gb-wi-fi-space-grey-mk2k3-2021',
    mainPhoto:
      'https://www.ctrs.com.ua/_next/image/?url=https://i.citrus.world/imgcache/size_180/uploads/shop/f/4/f4f665673380ce247486b1bf454e811c.jpg&w=256&q=60',
    rating: 4.5,
    bestSeller: true,
    totalPrice: 350,
    discountedPrice: 310,
    shortSpecs: [
      ['Display', 'Retina'],
      ['Screen Size', '10.2 inch'],
      ['Processor', 'Apple A13 Bionic'],
      ['CPU Cores', '6'],
      ['Memory Storage Capacity', '64 GB'],
    ],
  },
  {
    category: Category.tablets,
    name: 'Lenovo Tab M10 Plus (3rd Gen) 4/128 Wi-Fi Storm Grey (ZAAJ0373UA)',
    model: 'lenovo-tab-m10-plus-3rd-gen-4128-wi-fi-storm-grey-zaaj0373ua',
    mainPhoto:
      'https://content1.rozetka.com.ua/goods/images/big_tile/307109269.jpg',
    rating: 4.9,
    bestSeller: true,
    totalPrice: 230,
    discountedPrice: 190,
    shortSpecs: [
      ['Display', 'IPS'],
      ['Screen Size', '10.6 inch'],
      ['Processor', 'MediaTek Helio G80 (2.0 ГГц)'],
      ['CPU Cores', '4'],
      ['Memory Storage Capacity', '128 GB'],
    ],
  },
  {
    category: Category.tablets,
    name: 'Apple iPad Air 10.9" M1 Wi-Fi 64GB Space Gray (MM9C3RK/A)',
    model: 'apple-ipad-air-10-9-m1-wi-fi-64gb-space-gray-mm9c3rka',
    mainPhoto: 'https://content2.rozetka.com.ua/goods/images/big/259395025.jpg',
    rating: 4.6,
    bestSeller: false,
    totalPrice: 780,
    discountedPrice: 720,
    shortSpecs: [
      ['Display', 'IPS'],
      ['Screen Size', '10.9 inch'],
      ['Processor', 'Apple M1'],
      ['CPU Cores', '8'],
      ['Memory Storage Capacity', '64 GB'],
    ],
  },
  {
    category: Category.tablets,
    name: 'Apple iPad Pro 12.9" M2 Wi-Fi 128GB Silver (MNXQ3RK/A)',
    model: 'apple-ipad-pro-12-9-m2-wi-fi-128gb-silver-mnxq3rka',
    mainPhoto: 'https://content1.rozetka.com.ua/goods/images/big/301714807.jpg',
    rating: 3.3,
    bestSeller: false,
    totalPrice: 1450,
    discountedPrice: 1340,
    shortSpecs: [
      ['Display', 'Liquid Retina XDR'],
      ['Screen Size', '12.9 inch'],
      ['Processor', 'Apple M2'],
      ['CPU Cores', '8'],
      ['Memory Storage Capacity', '128 GB'],
    ],
  },
  {
    category: Category.tablets,
    name: 'Samsung Galaxy Tab S8 Ultra 5G 12/256GB Graphite (SM-X906BZAESEK)',
    model: 'samsung-galaxy-tab-s8-ultra-5g-12256gb-graphite-sm-x906bzaesek',
    mainPhoto:
      'https://content1.rozetka.com.ua/goods/images/big_tile/253290419.jpg',
    rating: 4.3,
    bestSeller: false,
    totalPrice: 1330,
    discountedPrice: 1190,
    shortSpecs: [
      ['Display', 'Super AMOLED'],
      ['Screen Size', '14.6 inch'],
      ['Processor', 'Qualcomm Snapdragon 8 Gen 1'],
      ['CPU Cores', '8'],
      ['Memory Storage Capacity', '128 GB'],
    ],
  },
] as CatalogItem[];
